### ISSUE TITLE
Message list doesn't update when messages change

### ISSUE THREAD

**Issue by selyon** [johniak/react-web-gifted-chat#10]
#### Issue Description

When a message is updated, for example changing the status from sent to received, the message list is not updated.
The problem is inside MessageContainer

`shouldComponentUpdate(nextProps) {
    const next = nextProps.messages;
    const current = this.props.messages;
    return (
      next.length !== current.length ||
      next.extraData !== current.extraData ||
      next.loadEarlier !== current.loadEarlier
    );
  }`

If i set received props of a message to true, (next.length !== current.length) this condition prevent the list from updating correctly.

**Comment by johniak** [comment]
fixed
