### ISSUE TITLE
Does the renderSystemMessage work?

### ISSUE THREAD

**Issue by smnodame** [johniak/react-web-gifted-chat#5]
#### Issue Description

I tried to use renderSystemMessage on web, but it do nothing and doesn't call my function anyway. I looked in the library, I did not see this function in propType

#### Additional Information

* Nodejs version: [8.10.0]
* React version: [16.3.1]
* React Native version: [0.55.2]
* react-native-gifted-chat version:
    - react-web-gifted-chat": "^0.1.3"
    - react-native-gifted-chat": "^0.6.0"
* Platform(s) (Web)

**Comment by johniak** [comment]
No, this is no implemented yet

**Comment by johniak** [comment]
System messages are now working
![screenshot 2019-01-17 at 21 26 35](https://user-images.githubusercontent.com/1036376/51348198-571c3000-1aa2-11e9-8593-9f42b86dcbd6.png)
