### ISSUE TITLE
Unknown event handler warnings

### ISSUE THREAD

**Issue by kaitlynbrown** [johniak/react-web-gifted-chat#9]
#### Issue Description

When using `react-web-gifted-chat`, I see a large number of warnings (logged as errors) in my console that seem to be coming from the a child of the `GiftedChat` component:
    
> Warning: Unknown event handler property `onResponderGrant`. It will be ignored.
> Warning: Unknown event handler property `onResponderMove`. It will be ignored.
> Warning: Unknown event handler property `onResponderRelease`. It will be ignored.
> Warning: Unknown event handler property `onResponderTerminate`. It will be ignored.
> Warning: Unknown event handler property `onResponderTerminationRequest`. It will be ignored.
> Warning: Unknown event handler property `onStartShouldSetResponder`. It will be ignored.
> Warning: Unknown event handler property `onStartShouldSetResponderCapture`. It will be ignored.
> Warning: Unknown event handler property `onScrollShouldSetResponder`. It will be ignored.
> Warning: Unknown event handler property `onResponderReject`. It will be ignored.

#### Steps to Reproduce / Code Snippets

Use the `GiftedChat` component as documented

#### Expected Results

No warning spam

#### Additional Information

* Nodejs version: 10.14.0
* React version: 16.8.0-alpha.1
* react-web-gifted-chat version: 0.6.2
* Browser(s) (Chrome, etc.): Chrome 70.0.3538.110

**Comment by johniak** [comment]
I have the same browser and gifted-chat version, and threre is no warning spam, I will check if the react version matters.
![image](https://user-images.githubusercontent.com/1036376/51733042-6b52c500-2080-11e9-8485-dc4321fbcd51.png)

**Comment by johniak** [comment]
Can you provide which props you passed to GiftedChat?

**Comment by lamtan92** [comment]
@johniak I got same warnning when add prop "loadEarlier={true}" .
Could you help check?

**Comment by ErMapsh** [comment]
@kaitlynbrown how did you solve it? in my observation this are native based event when we try on web its gives error like this
